name: Deploy React to GitHub Pages

on:
  push:
    branches:
      - main # Branch to deploy from

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Yarn
        run: corepack enable  # Ensures Yarn is available

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/.'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: 'https://larsflem.github.io/Maritime-Automation-Website/'
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Deploy
        uses: actions/deploy-pages@v4
